version: '3.8'
services:
  tariff-service-db:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tariff-service
    ports:
      - "6432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d tariff-service" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - tarificator-network

  tariff-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18002:18002"
    depends_on:
      - tariff-service-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://tariff-service-db/tariff-service
    networks:
      - tarificator-network
networks:
  tarificator-network:
    external: true